name: Rust Single File Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Change to Project Directory
      run: cd ./

    - name: Build
      run: rustc main.rs --crate-type bin --target x86_64-pc-windows-msvc -o my_program.exe

    - name: Setup Git Config
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'your-email@example.com'

    - name: Commit and Push
      run: |
        git add my_program.exe
        git commit -m "Add Windows executable"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
