name: Rust Single File Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Change to Project Directory
      run: cd ./

    - name: Build
      run: cargo build --release --target x86_64-pc-windows-msvc
    - name: tree
      run: tree /f ./
    - name: Rename and Move Executable
      run: move target\x86_64-pc-windows-msvc\release\passwd.exe passwd.exe


    - name: Setup Git Config
      run: |
        git config --global user.name 'auto'
        git config --global user.email 'auto@example.com'

    - name: Commit and Push
      run: |
        git add passwd.exe
        git commit -m "Add Windows executable"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
